groups:

- name: PrometheusRules

  rules:

    - alert: TargetDown
      expr: up == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: 监控目标（Target）丢失(实例:{{ $labels.instance }})
        description: "监控目标丢失"

    - alert: PrometheusConfigurationReloadFailure
      expr: prometheus_config_last_reload_successful != 1
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus配置文件重载失败（Instance:{{ $labels.instance }}）
        description: "Prometheus的配置文件重新加载失败"

    - alert: PrometheusNotConnectedToAlertmanager
      expr: prometheus_notifications_alertmanagers_discovered < 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Prometheus未连接到AlertManager (Instance:{{ $labels.instance }})
        description: "Prometheus未连接到AlertManager超过5分钟，可能是AlertManager运行不正常或未配置AlertManager"

    - alert: PrometheusNotificationsDropped
      expr: increase(prometheus_notifications_dropped_total[5m]) > 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus告警通知被丢弃（Instance:{{ $labels.instance }}）
        description: "5分钟内Prometheus丢弃了大约{{  $value }}个告警通知"

    - alert: PrometheusNotificationsBacklog
      expr: min_over_time(prometheus_notifications_queue_length[5m]) > 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus告警通知积压(Instance:{{ $labels.instance }})
        description: "5分钟内Prometheus积压了{{ $value }}条告警通知"      

    - alert: PrometheusNotReady
      expr: prometheus_ready != 1
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus服务运行不正常(Instance:{{ $labels.instance }})
        description: "Prometheus服务运行不正常"

    - alert: PrometheusRuleEvaluationFailed
      expr: increase(prometheus_rule_evaluation_failures_total[5m]) > 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus告警规则评估失败(Instance:{{ $labels.instance }})
        description: "5分钟内告警规则评估失败大约{{ $value }}次"

    - alert: PrometheusTemplateTextExpansionFailed
      expr: increase(prometheus_template_text_expansion_failures_total[5m]) > 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus模板文件扩展失败 (Instance:{{ $labels.instance }})
        description: "5分钟内模板文件扩展失败大约{{ $value }}次"

    - alert: PrometheusRuleGroupEvaluationSlow
      expr: prometheus_rule_group_last_duration_seconds > prometheus_rule_group_interval_seconds
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus规则组评估慢 (Instance:{{ $labels.instance }})
        description: "规则组{{ $labels.rule_group }}评估持续时间太长,时间为{{ $value }}"

    - alert: PrometheusScrapesSamplesRejected
      expr: increase(prometheus_target_scrapes_sample_duplicate_timestamp_total[5m]) > 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus异常样本被拒绝 (Instance:{{ $labels.instance }})
        description: "5分钟内Prometheus拒绝的异常样本数量大约为{{ $value }}"

    - alert: PrometheusTsdbCheckpointCreationsFailed
      expr: increase(prometheus_tsdb_checkpoint_creations_failed_total[5m]) > 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus tsdb 创建检查点失败 (Instance:{{ $labels.instance }})
        description: "5分钟内Prometheus出现大约{{ $value }}次创建检查点失败"

    - alert: PrometheusTsdbCheckpointDeletionsFailed
      expr: increase(prometheus_tsdb_checkpoint_deletions_failed_total[5m]) > 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus tsdb 删除检查点失败 (Instance:{{ $labels.instance }})
        description: "5分钟内Prometheus出现大约{{ $value }}次删除检查点失败"

    - alert: PrometheusTsdbCompactionsFailed
      expr: increase(prometheus_tsdb_compactions_failed_total[5m]) > 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus tsdb 数据压缩失败 (Instance:{{ $labels.instance }})
        description: "5分钟内Prometheus出现大约{{ $value }}次删数据压缩失败"

    - alert: PrometheusTsdbHeadTruncationsFailed
      expr: increase(prometheus_tsdb_head_truncations_failed_total[5m]) > 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus tsdb 头部数据删减失败 (Instance:{{ $labels.instance }})
        description: "5分钟内Prometheus出现大约{{ $value }}次头部数据块删减失败"

    - alert: PrometheusTsdbReloadsFailed
      expr: increase(prometheus_tsdb_reloads_failures_total[5m]) > 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus tsdb 数据重加载失败 (Instance:{{ $labels.instance }})
        description: "5分钟内Prometheus tsdb出现大约{{ $value }}次数据重加载失败"

    - alert: PrometheusTsdbWalTruncationsFailed
      expr: increase(prometheus_tsdb_wal_truncations_failed_total[5m]) > 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus tsdb 写入日志WAL删减失败 (Instance:{{ $labels.instance }})
        description: "5分钟内Prometheus tsdb出现大约{{ $value }}次写入日志WAL删减失败"

    - alert: PrometheusTsdbWalCorruptions
      expr: increase(prometheus_tsdb_wal_corruptions_total[5m]) > 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus tsdb的WAL损坏 (Instance:{{ $labels.instance }})
        description: "5分钟内Prometheus tsdb出现大约{{ $value }}次wal损坏"

    - alert: AlertManagerConfigReloadFailure
      expr: alertmanager_config_last_reload_successfull != 1
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: AlertManager配置文件重载失败(Instance:{{ $labels.instance }})
        description: "AlertManager的配置文件重新加载失败"


